on: [ push, pull_request ]
name: Test
jobs:
  unit-test:
    runs-on: ubuntu-18.04
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        stable: 'false'
        go-version: '1.18.0-beta1'
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: |
        go test -v ./...
