on: [ push, pull_request ]
name: Test
jobs:
  tcp-unit-test:
    runs-on: ubuntu-18.04
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: |
        cd tcp && go test -v ./...
